---
- name: start blackbox-exporter
  systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: "blackbox_exporter"
    state: started

- name: start grafana
  systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: "grafana-server"
    state: started

- name: start influxdb
  systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: "influxdb"
    state: started

- name: start prometheus
  systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: "prometheus"
    state: started

